title: Chapter One
author: Jatin Gohil
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Jatin from India. 
  Electronic engineering grad student with high interest in techonology & product management.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
